version: '3.9'

x-shared-environment: &shared-environment
  BUNDLE_PATH: /bundle_cache
  GEM_HOME: /bundle_cache
  GEM_PATH: /bundle_cache
  DB_HOST: db
  DB_USER: postgres
  DB_PASSWORD: postgres

x-shared-volumes: &shared-volumes
  - bundle_cache:/bundle_cache
  # - .:/app:cached
  # - ~/.bash_history:/root/.bash_history

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    working_dir: /app
    command: bash -c 'make lint && make test'
    volumes: *shared-volumes
    environment:
      <<: *shared-environment
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  bundle_cache:
