FROM ruby:3.0.2-alpine3.14

WORKDIR /app

ARG PACKAGES="nodejs yarn postgresql-client curl bash tzdata build-base postgresql-dev"

RUN apk update && apk upgrade && apk add --update --no-cache $PACKAGES

COPY Gemfile* /app

RUN bundle config set no-cache 'true' && bundle install --jobs 4

ADD . /app
